services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: raga-orders-app
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    depends_on:
      - db
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=olo_local
      - DB_USERNAME=postgres
      - DB_PASSWORD=ragaorders2026

  db:
    image: postgres:16
    container_name: raga-orders-db
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: olo_local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ragaorders2026
    volumes:
      - raga_postgres_data:/var/lib/postgresql/data
      - ./Olo_Orders_docker.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  raga_postgres_data:
