<?php

namespace App\Livewire\Forms;

use App\Models\Product;
use Livewire\Component;
use Carbon\Carbon;
use App\Models\Vendor;

class CreateProducts extends Component {
    // Product fields
    // Item ID is autogenerated in the database
    public $material_id;
    public $short_text;
    public $supplying_plant;
    public $unit_of_measure;
    public $plant;
    public $vendor_name;
    public $vendor_code;
    public $title;
    public $subtitle;
    public $btn_text;
    public $vendors = [];
    public $product;
    public $vendor_id;
    public $price_per_unit;
    public $is_editing = false;
    public $qty_unit;

    // Arrays for select options
    public $qtyUnitOptions = ["kg" => "Kilogramos", "pcs" => "Piezas", "lt" => "Litros", "m" => "Metros"];
    public $vatRateOptions = ["0" => "0%", "16" => "16%", "8" => "8%"];

    public function mount($product = null)
    {
        $vendors = Vendor::all();
        $this->vendors = $vendors->mapWithKeys(function ($vendor) {
            return [$vendor->vendo_code => $vendor->name];
        });

        if ($product) {
            $this->product = $product;
            $this->material_id = $product->material_id;
            $this->short_text = $product->short_text;
            $this->supplying_plant = $product->supplying_plant;
            $this->unit_of_measure = $product->unit_of_measure;
            $this->plant = $product->plant;
            $this->vendor_code = $product->vendo_code;
            $this->price_per_unit = $product->price_per_unit;
            $this->title = "Editar Producto";
            $this->subtitle = "Ingrese los datos para editar el producto";
            $this->btn_text = "Editar Producto";
            $this->is_editing = true;
        } else {
            $this->title = "Crear Producto";
            $this->subtitle = "Ingrese los datos para crear un nuevo producto";
            $this->btn_text = "Crear Producto";
            $this->is_editing = false;
        }
    }

    public function createProduct()
    {
        // Validate form
        $this->validate([
            'material_id' => 'required|string|max:50',
            'short_text' => 'required|string',
            'supplying_plant' => 'nullable|string|max:100',
            'unit_of_measure' => 'nullable|string|max:100',
            'plant' => 'nullable|string|max:100',
        ]);

        // Create product
        $product = Product::create([
            'material_id' => $this->material_id,
            'short_text' => $this->short_text,
            'supplying_plant' => $this->supplying_plant,
            'unit_of_measure' => $this->unit_of_measure,
            'plant' => $this->plant,
            'vendo_code' => $this->vendor_code,
            'price_per_unit' => $this->price_per_unit,
        ]);

        // Reset form
        $this->reset();

        // Dispatch event to open modal
        $this->dispatch('open-modal', 'modal-product-created');
    }

    public function closeModal() {
        $this->dispatch('close-modal', 'modal-product-created');
        return redirect()->route('products.index');
    }

    public function updateProduct()
    {
        $this->product->update([
            'material_id' => $this->material_id,
            'short_text' => $this->short_text,
            'supplying_plant' => $this->supplying_plant,
            'unit_of_measure' => $this->unit_of_measure,
            'plant' => $this->plant,
            'vendo_code' => $this->vendor_code,
            'price_per_unit' => $this->price_per_unit,
        ]);

        // Dispatch event to open modal
        $this->dispatch('open-modal', 'modal-product-created');
    }

    // Calculate net value when price or quantity changes
    public function updatedOrderQuantity()
    {
        //$this->calculateNetValue();
    }

    public function updatedPricePerUnit()
    {
        //$this->calculateNetValue();
    }

    public function updatedVatRate()
    {
        //$this->calculateVatValue();
    }

    private function calculateNetValue()
    {
        if (is_numeric($this->order_quantity) && is_numeric($this->price_per_unit)) {
            $this->net_value = $this->order_quantity * $this->price_per_unit;
            $this->calculateVatValue();
        }
    }

    private function calculateVatValue()
    {
        if (is_numeric($this->net_value) && is_numeric($this->vat_rate)) {
            $this->vat_value = $this->net_value * ($this->vat_rate / 100);
        }
    }

    public function render() {
        return view('livewire.forms.create-products');
    }
}
